#
# Descriptive metadata
#

url: http://nxtv.cz
title: nxtv.cz
description: Open source powered TV channel
keywords: Broadcast, Creative commons, Open source, Independent, Television
language: en
author: imm studios, z.s.
copyright: Page created by imm studios under Creative Commons - Attribution - Share alike license (CC-BY-SA)  3.0

analytics: UA-51103561-1

#
# Build options
#

exclude: ["_doc", "LICENSE", "README.md"]
