#
# Descriptive metadata
#

title: nxtv
description: nezávislá televizní stanice
keywords: open source, broadcast
language: cz
author: imm studios, z.s.

#
# Build options
#

exclude: ["_doc", "LICENSE", "README.md"]
markdown: redcarpet
pygments: true