#
# Descriptive metadata
#

url: http://nxtv.cz
title: nxtv.cz
description: Nekomerční televizní stanice založená na otevřených technologiích a svobodném obsahu
keywords: Broadcast, Creative commons, Open source, Independent, Television, televize, nezávislý, televizní vysílání, rock, indie, alternative, alternativní
language: cz
author: imm studios, z.s.
copyright: Tato stránka je licencována pod Creative Commons - Attribution - Share alike license (CC-BY-SA)  3.0

analytics: UA-51103561-1

#
# Build options
#

exclude: ["_doc", "LICENSE", "README.md"]
